--- 
- hosts: convsrc2
  become: true
  roles:
    - syslog

- hosts: convsrc_net2
  become: true
  roles:
    - trafgen

- hosts: conntrack
  become: true
  roles:
    - connectionTracking
    - keepalived
    - ptp

